[versions]
adventure = "4.13.1"
bstats = "3.0.2"
cloud = "1.8.3"

[libraries]
# Bstats
bstats-velocity = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }

# Cloud
cloud-core = { module = "cloud.commandframework:cloud-core", version.ref = "cloud" }
cloud-bungeecord = { module = "cloud.commandframework:cloud-bungee", version.ref = "cloud" }
cloud-velocity = { module = "cloud.commandframework:cloud-velocity", version.ref = "cloud" }

# Configuration
dazzleconf = { module = "space.arim.dazzleconf:dazzleconf-ext-snakeyaml", version = "1.3.0-M1" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "1.33" }

# Google
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
guava = { module = "com.google.guava:guava", version = "31.1-jre" }

# Adventure
adventure-platform-bungeecord = { module = "net.kyori:adventure-platform-bungeecord", version = "4.3.0" }
adventure-api = { module = "net.kyori:adventure-api", version.ref= "adventure" }
minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }

# Platforms
waterfall-api = { module = "io.github.waterfallmc:waterfall-api", version = "1.19-R0.1-SNAPSHOT" }
velocity-api = { module = "com.velocitypowered:velocity-api", version = "3.1.1" }

# Other
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.7" }
partyAndFriends-bungeecord = { module = "de.simonsator:BungeecordPartyAndFriends", version = "1.0.89" }
partyAndFriends-velocity = { module = "de.simonsator:VelocityPoweredPartyAndFriends", version = "1.0.89" }
premiumvanish = { module = "com.github.LeonMangler:PremiumVanishAPI", version = "2.7.11-2" }

[plugins]
blossom = { id = "net.kyori.blossom", version = "1.3.1" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
pluginYml-bungee = { id = "net.minecrell.plugin-yml.bungee", version = "0.5.3" }